[workspace]
members = ["cmd_macros"]

[package]
name = "votv-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = { git = "https://github.com/raylib-rs/raylib-rs.git", branch = "unstable" }
cmd_macros = { path = "cmd_macros" }
