[workspace]
members = ["iter", "textedit"]

[package]
name = "votv-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
iter = { path = "iter" }
textedit = { path = "textedit" }
